use_frameworks!

platform :ios, '12.0'

target 'jionews-shortssdk-cocoapod_Example' do
  pod 'jionews-shortssdk-cocoapod', :path => '../'

  target 'jionews-shortssdk-cocoapod_Tests' do
    inherit! :search_paths

    
  end
end
